/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    `java-library`
    kotlin("jvm") version "1.9.10"

}


dependencies {
/*    api("org.springframework.boot:spring-boot-starter-data-jpa:3.1.2")
    api("org.springframework.hateoas:spring-hateoas:2.0.1")
    api("com.mysql:mysql-connector-j:8.0.31")
    api("com.fasterxml.jackson.core:jackson-annotations:2.14.0")
    runtimeOnly("org.hibernate:hibernate-core:5.2.17.Final")
    testImplementation("org.springframework.boot:spring-boot-starter-test:3.0.1")

    api("org.springframework.boot:spring-boot-starter-validation:3.1.2")
    api("org.hibernate.validator:hibernate-validator:8.0.0.Final")
    api("javax.validation:validation-api:2.0.1.Final")
    api("com.fasterxml.jackson.module:jackson-module-kotlin:2.11.4")
    api("javax.persistence:javax.persistence-api:2.2")
    api("org.jetbrains.kotlin:kotlin-reflect:1.9.0")
    api("org.jetbrains.kotlin:kotlin-maven-allopen:1.9.0")
    testImplementation("org.junit.jupiter:junit-jupiter-api:5.9.1")
    compileOnly("jakarta.servlet:jakarta.servlet-api:6.0.0")*/
}



tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}
