/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    kotlin("jvm") version "1.9.10"
    //spring plugin
}

repositories {
    mavenCentral()
       maven {
           url = uri("https://repo.maven.apache.org/maven2/")
       }
}


group = "com.epam.esm"
version = "1.0-SNAPSHOT"

subprojects {
    repositories {
        mavenCentral()
           maven {
               url = uri("https://repo.maven.apache.org/maven2/")
           }
    }
//    java.sourceCompatibility = JavaVersion.VERSION_17

}
