plugins {
    id("org.gradle.toolchains.foojay-resolver-convention") version "0.5.0"
}
/*
 * This file was generated by the Gradle 'init' task.
 */

rootProject.name = "Rest-api-basics-task"
include("nats")
include("tag-subdomain")
include("gift-certificate-subdomain")
include("order-subdomain")
include("user-subdomain")
include("shared-subdomain")
