/*
 * This file was generated by the Gradle 'init' task.
 */


plugins {
    `java-library`
    kotlin("jvm") version "1.9.10"

}


dependencies {
/*    api(project(":persistence"))
    api("org.springframework.security:spring-security-core:5.4.0")
    testImplementation("org.mockito:mockito-junit-jupiter:4.11.0")

    api("org.jetbrains.kotlin:kotlin-stdlib:1.9.0")
    api("org.springframework.boot:spring-boot-starter-validation:3.1.2")
    api("org.hibernate.validator:hibernate-validator:8.0.0.Final")
    api("javax.validation:validation-api:2.0.1.Final")
    api("com.fasterxml.jackson.module:jackson-module-kotlin:2.11.4")
    api("javax.persistence:javax.persistence-api:2.2")
    api("org.jetbrains.kotlin:kotlin-reflect:1.9.0")
    api("org.jetbrains.kotlin:kotlin-maven-allopen:1.9.0")
    testImplementation("org.junit.jupiter:junit-jupiter-api:5.9.1")
    compileOnly("jakarta.servlet:jakarta.servlet-api:6.0.0")*/
}



tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}
