/*
 * This file was generated by the Gradle 'init' task.
 */


plugins {
    java
    kotlin("jvm") version "1.9.10"

}


dependencies {
/*    implementation("org.springframework.boot:spring-boot-starter-security:2.4.5")
    implementation("org.springframework.boot:spring-boot-starter-web:2.4.5")
    implementation("org.springframework.boot:spring-boot-starter-oauth2-client:2.4.5")
    implementation(project(":service"))
    implementation("io.jsonwebtoken:jjwt:0.9.0")
    testImplementation("org.springframework.boot:spring-boot-starter-test:2.4.5")

    implementation("org.jetbrains.kotlin:kotlin-stdlib:1.9.0")
    implementation("org.springframework.boot:spring-boot-starter-validation:3.1.2")
    implementation("org.hibernate.validator:hibernate-validator:8.0.0.Final")
    implementation("javax.validation:validation-api:2.0.1.Final")
    implementation("com.fasterxml.jackson.module:jackson-module-kotlin:2.11.4")
    implementation("javax.persistence:javax.persistence-api:2.2")
    implementation("org.jetbrains.kotlin:kotlin-reflect:1.9.0")
    implementation("org.jetbrains.kotlin:kotlin-maven-allopen:1.9.0")
    testImplementation("org.junit.jupiter:junit-jupiter-api:5.9.1")
    compileOnly("jakarta.servlet:jakarta.servlet-api:6.0.0")*/
}



tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}
